name: Linux build
on: [push, pull_request]
jobs:
  linux:
    name: build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.13'
          java-package: jdk
          architecture: x64
          distribution: microsoft
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
