name: Linux build
on: [push, pull_request]
jobs:
  linux:
    name: build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.13'
          java-package: jdk
          architecture: x64
          distribution: microsoft
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: build/linux/x64/release/bundle
      - run: tar jcvf minigames-linux-release-x64.tar.bz2 -C build/linux/x64/release bundle
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: minigames-linux-release-x64.tar
