name: Web build
on: [push, pull_request]
jobs:
  web:
    name: build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.13'
          java-package: jdk
          architecture: x64
          distribution: microsoft
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@v2
        with:
          name: web-release
          path: build/web
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r minigames-web-release.zip build/web
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: minigames-web-release.zip
