name: Windows build
on: [push, pull_request]
jobs:
  windows:
    name: build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.13'
          java-package: jdk
          architecture: x64
          distribution: microsoft
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: build/windows/runner/Release
